version: 0.2

env:
  parameter-store:
    CYPRESS: /Cypress/Tools/Key

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install cypress --save-dev
  build:
    commands:
      - npx cypress run --config-file ${CONFIG} --headless --record --key=$CYPRESS --tag "${ENVIRONMENT}"
