version: 0.2

env:
  parameter-store:
    CYPRESS: /Cypress/Tools/Key

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install cypress --save-dev
  build:
    commands:
      - echo $COMMIT_ID
      - echo $COMMIT_MSG
      - echo $COMMIT_URL
      - COMMIT_INFO_BRANCH=Master COMMIT_INFO_SHA=$COMMIT_ID COMMIT_INFO_MESSAGE=$COMMIT_MSG npx cypress run --config-file ${CONFIG} --headless --record --key=$CYPRESS --tag "${ENVIRONMENT},pipeline"
