version: 0.2

env:
  parameter-store:
    CYPRESS: /Cypress/Tools/Key

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install cypress --save-dev
  build:
    commands:
      - URL=$(echo $COMMIT_URL | sed 's/api.github.com\/repos/github.com/' | sed 's/git\/commits/commit/')
      - COMMIT_INFO_BRANCH=Master COMMIT_INFO_SHA=$COMMIT_ID COMMIT_INFO_MESSAGE=$COMMIT_MSG COMMIT_INFO_REMOTE=$URL CYPRESS_TEST_TAGS=$TEST_TAG npx cypress run --config-file ${CONFIG} --headless --record --key=$CYPRESS --tag "${ENVIRONMENT},pipeline"
