version: 0.2

env:
  parameter-store:
    CYPRESS: /Cypress/Tools/Key
  variables:
    PROFILE: "webdeploy"

# AWS CodeBuild Batch configuration
# https://docs.aws.amazon.com/codebuild/latest/userguide/batch-build-buildspec.html
# Define 5 parallel builds to run using the "cypress/base" image on DockerHub
batch:
  fast-fail: false
  build-list:
    - identifier: cypress1
      env:
        variables:
          IMAGE: cypress/base
    - identifier: cypress2
      env:
        variables:
          IMAGE: cypress/base
    - identifier: cypress3
      env:
        variables:
          IMAGE: cypress/base
    - identifier: cypress4
      env:
        variables:
          IMAGE: cypress/base
    - identifier: cypress5
      env:
        variables:
          IMAGE: cypress/base

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install cypress --save-dev
  pre_build:
    commands:
      - ROLE_ARN="arn:aws:iam::$ACCOUNT_ID:role/$BUILD_CROSS_ACCOUNT_ROLE"
      - TEMP_ROLE=$(aws sts assume-role --role-arn "$ROLE_ARN" --role-session-name "$PROFILE")
      - echo $TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $PROFILE
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $PROFILE
      - aws configure set aws_session_token $AWS_SESSION_TOKEN --profile $PROFILE
  #     - npm run cy:verify
  #     - npm run cy:info
  #     - echo "Codebuild Initiator $CODEBUILD_INITIATOR"
  build:
    # Per https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
    # use $CODEBUILD_INITIATOR as it provides the entity that started the build
    # which is unique and can be used as the --ci-build-id for the Cypress Dashboard
    # e.g. awsCodeBuild-cypress-kitchen-sink/AWSCodeBuild-a14fc8e3-b5d6-42f9-9067-345d48a8f0fd
    commands:
      - URL=$(echo $COMMIT_URL | sed 's/api.github.com\/repos/github.com/' | sed 's/git\/commits/commit/')
      - COMMIT_INFO_BRANCH=Master COMMIT_INFO_SHA=$COMMIT_ID COMMIT_INFO_MESSAGE=$COMMIT_MSG COMMIT_INFO_REMOTE=$URL CYPRESS_TEST_TAGS=$TEST_TAG npx cypress run --config-file ${CONFIG} --headless --record --parallel --ci-build-id $CODEBUILD_INITIATOR --key=$CYPRESS --tag "$ENVIRONMENT,$TEST_TAG,pipeline"
